#!/usr/bin/env zsh

# Path to your oh-my-zsh installation.
export ZSH=${HOME}/.oh-my-zsh

# Uncomment the following line to use case-sensitive completion.
CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
export PROFILE_PATH="$HOME/development/profile"
ZSH_CUSTOM="$PROFILE_PATH/omz/custom"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

# add plugins=(osx) for the tab command, to command-click a vim file in new tab
# also need to add 'tab' in iterm2 profile/advanced semantic history
# plugins=(git)

### testing ###
# DEBUG_TIME_TEST=true PREVIOUS_TIME=0 # uncomment this to speedtest
typeset -F SECONDS # much smaller than seconds
time_test(){
  if [[ ${DEBUG_TIME_TEST} == true ]]; then
    TOTAL_TIME="$(echo "${SECONDS}-0" | bc)"
    SINCE_PREVIOUS_TEST="$(echo "${SECONDS}-${PREVIOUS_TIME:-0}" | bc)"
    echo "[INFO] ${SINCE_PREVIOUS_TEST} ${*}"
    PREVIOUS_TIME=$SECONDS
  fi
}
time_test "[$(basename -- "${(%):-%x}")] starting debug time_test"
### end debug init ###

ZSH_THEME="powerlevel10k/powerlevel10k"
# ZSH_THEME="crunch_custom"
zstyle ':omz:update' mode disabled # https://github.com/ohmyzsh/ohmyzsh#getting-updates
zstyle ':omz:plugins:docker' aliases no
zstyle ':omz:plugins:git' aliases no

plugins=(aws git docker zsh-autosuggestions)

source "$ZSH/oh-my-zsh.sh"

time_test "[$(basename -- "${(%):-%x}")] loaded oh-my-zsh.sh"

# User configuration
source "$PROFILE_PATH/omz/zshrc.custom"

### debug ###
if [[ ${DEBUG_TIME_TEST} == true ]] then;
  echo "[FULL] ${TOTAL_TIME} [$(basename -- "${(%):-%x}")]"
fi
