#!/usr/bin/env bash

set -e

# git change to default branch and pull from remote

PURPLE="\033[0;35m"
WHITE="\033[0m"
currentbranch=$(git rev-parse --abbrev-ref HEAD)

check_default_branch(){
    git remote show origin | awk '/^  HEAD branch:/ {print $NF}'
    # git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'
}

check_submodule_list(){
    SUBMODULE_LIST=$(git submodule)
}

header(){
    echo -e "[${PURPLE}${1}${WHITE}]"
}

gitColor(){
    git -c color."${1}"=always "${@}"
}

pull_default_branch(){
    default_branch="$(check_default_branch)"
    if [ "${currentbranch}" != "${default_branch}" ]; then
        header "Switching to ${default_branch} branch"
        gitColor checkout "${default_branch}"
    fi
    header "Pulling ${default_branch}"
    gitColor pull --rebase --prune
    check_submodule_list
    if [ "$SUBMODULE_LIST" ]; then
        header "Git Submodule Update"
        gitColor submodule sync --recursive && \
            gitColor submodule update --init --recursive --depth 1
    fi
}


pull_default_branch
