#!/usr/bin/env bash
# source this script to set KUBECTL_NAMESPACE variable for your current shell

NEW_NAMESPACE="$1"
[ "$KUBECTL_NAMESPACE" ] || export KUBECTL_NAMESPACE=default

exit_code(){
    (exit $exitCode)
}


if [ ! "$NEW_NAMESPACE" ]; then
    echo "ERROR no namespace provided"
    echo "usage: source $0 <new-namespace>"
    exitCode=1
# if namespace is passed and is not already defined
elif [ "$NEW_NAMESPACE" != "$KUBECTL_NAMESPACE" ]; then
    echo -e "kubectl changing namespace from \"$KUBECTL_NAMESPACE\" to \"$NEW_NAMESPACE\""
    export KUBECTL_NAMESPACE="$NEW_NAMESPACE"
    exitCode=0
else
    echo "kubectl namespace already set to \"$KUBECTL_NAMESPACE\""
    exitCode=2
fi

# This runs in a subshell, so it will not exit your shell when you are sourcing,
# but it still gives you the correct exit code if you read from $?
exit_code
